In [19]:
! pip install pandas

'pip' is not recognized as an internal or external command,
operable program or batch file.

In [20]:
! pip install pandas

'pip' is not recognized as an internal or external command,
operable program or batch file.

In [21]:
!python -m pip install pandas

Requirement already satisfied: pandas in c:\users\harru\appdata\local\python\pythoncore-3.14-64\lib\site-packages (3.0.1)
Requirement already satisfied: numpy>=2.3.3 in c:\users\harru\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\harru\appdata\roaming\python\python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\harru\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\harru\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [22]:
import pandas as pd
pd.__version__

'3.0.1'

In [23]:
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35]
}

df = pd.DataFrame(data)
df

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [24]:
import os
os.listdir()

['usedbikes2_basics.ipynb',
 'usedbikes_basics.ipynb',
 'Used_Bikes (1).csv',
 'Used_Bikes (2).csv',
 'used_bikes.ipynb',
 'used_bikes.sipynb']

In [25]:
import pandas as pd

df = pd.read_csv("Used_Bikes (1).csv")
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [26]:
df.columns

Index(['bike_name', 'price', 'city', 'kms_driven', 'owner', 'age', 'power',
       'brand'],
      dtype='str')

In [27]:
df.columns

Index(['bike_name', 'price', 'city', 'kms_driven', 'owner', 'age', 'power',
       'brand'],
      dtype='str')

In [28]:
# Increase price by 10%
df["price"] = df["price"] * 1.10

In [29]:
# Change price of first row
df.loc[0, "price"] = 50000

In [30]:
df.head()

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,50000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,131890.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,660000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,71500.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,88000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha

In [31]:
# Change price of first row
df.loc[0, "price"] = 50000
df.head()

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,50000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,131890.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,660000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,71500.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,88000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha

In [32]:
# Sort bikes by price in ascending order
df_sorted = df.sort_values(by="price")

df_sorted.head()

,bike_name,price,city,kms_driven,owner,age,power,brand
4960,LML Freedom DX 110cc,4840.0,Godhara,55000.0,First Owner,16.0,110.0,LML
9194,Hero Ambition 135cc,5500.0,Delhi,82178.0,First Owner,18.0,135.0,Hero
9301,Hero Ambition 135cc,5500.0,Delhi,82178.0,First Owner,18.0,135.0,Hero
1382,TVS Flame 125cc,6380.0,Ghaziabad,25000.0,First Owner,13.0,125.0,TVS
1437,TVS Flame 125cc,6380.0,Ghaziabad,25000.0,First Owner,13.0,125.0,TVS

In [33]:
# Sort bikes by price in descending order
df_sorted = df.sort_values(by="price", ascending=False)

df_sorted.head()

,bike_name,price,city,kms_driven,owner,age,power,brand
367,Indian Chief Classic 1800cc,2090000.0,Chennai,1700.0,First Owner,6.0,1800.0,Indian
4864,BMW S 1000 RR Pro,1980000.0,Delhi,2600.0,First Owner,4.0,1000.0,BMW
7671,Yamaha YZF-R1 1000cc,1705000.0,Delhi,9800.0,Second Owner,6.0,1000.0,Yamaha
6872,MV Agusta F3 800cc,1650000.0,Hubli,2000.0,First Owner,3.0,800.0,MV
3016,BMW S 1000 XR Pro,1650000.0,Delhi,18000.0,First Owner,4.0,1000.0,BMW

In [34]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,50000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,131890.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,660000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,71500.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,88000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
32643,Hero Passion Pro 100cc,42900.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,33000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,66000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,17160.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,24200.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [35]:
import pandas as pd

# 1. File load karein (Bracket waala naam use karein jo explorer mein hai)
df = pd.read_csv("Used_Bikes (1).csv") 

# 2. Owner column ke liye dictionary
owner_dict = {
    'First Owner': 1,
    'Second Owner': 2,
    'Third Owner': 3,
    'Fourth Owner Or More': 4
}

# 3. Encoding apply karein
# .get() use karne se error nahi aayega agar koi value match na ho
df['owner'] = df['owner'].map(owner_dict)

# 4. Result check karein
df.head()

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,1,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,1,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,1,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,1,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,1,3.0,150.0,Yamaha

In [36]:
! pip install scikit-learn

'pip' is not recognized as an internal or external command,
operable program or batch file.

In [2]:
import pandas as pd

# Load CSV file
df = pd.read_csv("Used_Bikes(1).csv")

# Display data
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'Used_Bikes(1).csv'